###
GET http://localhost:8080/

###
GET http://localhost:8080/swagger-ui.html

###
GET http://localhost:8080/v2/api-docs

###
GET http://localhost:8080/books

###
GET http://localhost:8080/users/find?name=vivedk

###
GET http://localhost:8080/users

###
POST http://localhost:8080/users HTTP/1.1 
content-type: application/json

{ "name":"U1", "borrowLimit":1 }


###
POST http://localhost:8080/users HTTP/1.1 
content-type: application/json

{ "name":"U2", "borrowLimit":2 }

###
POST http://localhost:8080/books HTTP/1.1 
content-type: application/json

{ "title":"B1", "author":"A1", "copies":2 }

###
POST http://localhost:8080/books HTTP/1.1 
content-type: application/json

{ "title":"B2", "author":"A1", "copies":1 }


###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"B1", "author":"A1"},
"user":{"name":"U1"}}

###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"B2", "author":"A1"},
"user":{"name":"U1"}}

###
POST http://localhost:8080/return HTTP/1.1 
content-type: application/json

{"book":{ "title":"B1", "author":"A1"},
"user":{"name":"U1"}}

###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"B2", "author":"A1"},
"user":{"name":"U1"}}

###
POST http://localhost:8080/return HTTP/1.1 
content-type: application/json

{"book":{ "title":"B1", "author":"A1"},
"user":{"name":"U1"}}

###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"B1", "author":"A1"},
"user":{"name":"U2"}}

###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"B2", "author":"A1"},
"user":{"name":"U2"}}

###
POST http://localhost:8080/return HTTP/1.1 
content-type: application/json

{"book":{ "title":"B2", "author":"A1"},
"user":{"name":"U1"}}

###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"B1", "author":"A1"},
"user":{"name":"U1"}}

###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"B1", "author":"A1"},
"user":{"name":"UX"}}












###
POST http://localhost:8080/books HTTP/1.1 
content-type: application/json

{ "title":"ABC1", "author":"xyz", "copies":1 }

###
POST http://localhost:8080/books HTTP/1.1 
content-type: application/json

{ "title":"BCD", "author":"abc", "copies":5 }

###
POST http://localhost:8080/books HTTP/1.1 
content-type: application/json

{ "title":"ABC2", "author":"xyz", "copies":8 }

###
POST http://localhost:8080/lend HTTP/1.1 
content-type: application/json

{"book":{ "title":"BCD", "author":"abc"},
"user":{"name":"vivek1"}}

###
POST http://localhost:8080/return HTTP/1.1 
content-type: application/json

{"book":{ "title":"ABC2", "author":"xyz", "copies":8 },
"user":{"name":"vivek"}}